module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        spacing: {
            1: "8px",
            2: "12px",
            3: "16px",
            4: "24px",
            5: "32px",
            6: "48px",
            7: "56px",
            8: "64px",
            9: "80px",
            10: "96px",
            11: "112px",
            12: "128px",
            14: "144px",
            16: "160px",
            20: "176px",
            24: "208px",
            28: "240px",
            32: "272px",
        },
        fontSize: {
            xs: "10px",
            sm: "12px",
            tiny: "8px",
            base: "16px",
            lg: "24px",
            xl: "32px",
            "2xl": "40px",
            "3xl": "48px",
            "4xl": "56px",
            "5xl": "64px",
            "6xl": "72px",
            "7xl": "80px",
        },

        fontFamily: {
            sans: ["Inter", "sans-serif"],
            serif: ["Merriweather", "serif"],
        },
        borderRadius: {
            xs: "4px",
            sm: "8px",
            tiny: "2px",
            base: "8px",
            lg: "8px",
            xl: "8px",
        },
        extend: {
            colors: {
                brown: {
                    900: "#1C0B05",
                    800: "#34190F",
                    700: "#4D2D1F",
                    600: "#674433",
                    500: "#84604D",
                    400: "#A17F6D",
                    300: "#BFA493",
                    200: "#DCCCBF",
                    100: "#EEE5DF",
                    50: "#F9F5F1",
                },
            },
        },
    },
    plugins: [],
};
