module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        spacing: {
            1: "8rem",
            2: "12rem",
            3: "16rem",
            4: "24rem",
            5: "32rem",
            6: "48rem",
            7: "56rem",
            8: "64rem",
            9: "80rem",
            10: "96rem",
            11: "112rem",
            12: "128rem",
            14: "144rem",
            16: "160rem",
            20: "176rem",
            24: "208rem",
            28: "240rem",
            32: "272rem",
        },
        fontSize: {
            xs: "10rem",
            sm: "12rem",
            tiny: "8rem",
            base: "16rem",
            lg: "24rem",
            xl: "32rem",
            "2xl": "40rem",
            "3xl": "48rem",
            "4xl": "56rem",
            "5xl": "64rem",
            "6xl": "72rem",
            "7xl": "80rem",
        },

        fontFamily: {
            sans: ["Inter", "sans-serif"],
            serif: ["Merriweather", "serif"],
        },
        borderRadius: {
            xs: "4rem",
            sm: "8rem",
            tiny: "2rem",
            base: "8rem",
            lg: "8rem",
            xl: "8rem",
        },
        extend: {
            colors: {
                brown: {
                    900: "#1C0B05",
                    800: "#34190F",
                    700: "#4D2D1F",
                    600: "#674433",
                    500: "#84604D",
                    400: "#A17F6D",
                    300: "#BFA493",
                    200: "#DCCCBF",
                    100: "#EEE5DF",
                    50: "#F9F5F1",
                },
            },
        },
    },
    plugins: [],
};
